### ISSUE TITLE
Tests fail for installed package due to missing file

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/redland-bindings#10]
The test.redland_base.R test fails due to the missing file dc.rdf.

**Comment by sbpcs59** [comment]
Added ./inst/testfiles/dc.rdf to fix this in commit https://github.com/ropensci/redland-bindings/commit/11ea83676996e29b155f14d84bae2d3696b3a9fe

**Comment by mbjones** [comment]
@sbpcs59 that file ships with the redland-bindings package in the data directory.  The tests were passing for me using the path that I had provided.  What changed? How are you running the tests when it is failing?  It would be better to not copy the file in the repo, but if its necessary to have it inside the R package, then it could be copied into place by the Makefile.am script.  That way there is only one copy to maintain.  Thoughts?

**Comment by sbpcs59** [comment]
Fixed by copying the file ./redland-bindings/data/dc.rdf to R/redland/inst/testfiles from R/Makefile (in commit f61ff3ad4fef1821395e77dc4a13bbb9f646747f )
