### ISSUE TITLE
Dependency rules in R/Makefile.am need to be updated

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/redland-bindings#18]
R/Makefile.am refers to files that are now located in the redland/src directory, i.e. redland.c, redland.o, and
not the current directory. Update the dependency rules so that the targets are not executed every time.

**Comment by sbpcs59** [comment]
The R package now builds cleanly/passes tests from a newly cloned tree with changes through commit daa4d2eeb6d24687b2f1b1d6a6aa197d458c4782

The process to build and test from newly cloned source tree:

- cd redlands-bindings
- ./autogen.sh --with-R
- make
- make check

**Comment by mbjones** [comment]
@sbpcs59 so awesome!
