### ISSUE TITLE
Resolve any issues reported from R CMD check for R build

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/redland-bindings#19]

**Comment by sbpcs59** [comment]
One WARNING flagged by "R CMD check" is the undocumented fuctions from the SWIG wrapper
file redland/R/redland.R that are visible to the user but can't be documented via Roxygen tags as the
code is generated during development tree installation / config. At one time SWIG had a documentation
module, (for Python, Java) but this has been removed and it's not clear when it may be reimplemented.

These routines of course are not intended to be called by users of the redland package, as we provide the wrapper to them, so they don't really need to be documented, but this WARNING will require an
explanation with the CRAN submission, which slows down the submission process.

Any ideas how to resolve this?

**Comment by cboettig** [comment]
Hmm, that's a really good question.  Have you tried asking on the roxygen and/or rdevtools email lists for a recommendation here?  (roxygen-devel@r-forge.wu-wien.ac.at, rdevtools@googlegroups.com).

If they aren't intended for users, is there a way to simply avoid exporting them in the Namespace in the first place/removing them from an auto-generated Namespace?  (Sorry if that's an ignorant question and you've already been down that route).

**Comment by mbjones** [comment]
Good point, @cboettig -- Although we built the higher level R classes and API, there's a lot of redland functions in the low level API that users might in fact want to access.  Which is why I added them to the Namespace.  Certainly could be reconsidered, and maybe that's a good stopgap to get v1 of the module published.  The redland functions have a great set of documentation, so I wonder if we could automate the translation of that to .Rd format rather than rewriting the docs or copy/pasting.

**Comment by sbpcs59** [comment]
The redland library functions that are wrapped in R/redland.R are well documented on http://librdf.org/docs/api/, so is it reasonable to create an .rd file for each function that redirects (@references) the user to that site? This could be done in the mergeNamespace.R roclet when
document() is run. There are 217 functions exposed in redland.R, so copy/paste is unwieldy. Regarding
translating librdf.org docs to .rd format, I don't see any alternative to html scraping.

**Comment by mbjones** [comment]
I think the redland docs are in structured pod format here: https://github.com/dajobe/librdf/tree/master/docs

We should be able to parse those, and maybe convert to Rd format.

**Comment by sbpcs59** [comment]
Using Docker to test the R devel CRAN tests as outlined in http://emhart.info/blog/2015/04/07/docker-r/,
the redland package triggers one NOTE (because it's a new package, and can't be cleared) and one WARNING:

* checking whether package ‘redland’ can be installed ... WARNING
Found the following significant warnings:
  WARNING: ignoring environment value of R_HOME

which appears to be an problem with R-devel and not the package, as this warning doesn't happen
on any other version of R, with the command 'CMD check --as-cran redland_1.0.17.tar.gz'

So, I believe the package is 'clean'.
