### ISSUE TITLE
Design R API and classes for redland bindings

### ISSUE THREAD

**Issue by mbjones** [ropensci/redland-bindings#2]
The low-level redland API can be somewhat difficult to grok.  So many of the binding languages have produced a higher-level API with core classes representing RDF models, statements and nodes.  We could design a similar API for R using S4 classes, or we could have the API match the existing `rrdf` package. This ticket is to discuss and conclude what API design we should implement.

This table shows the redland bindings concepts and classes in Python and proposed class names for R.

|  Concept |  Redland Class | R Class | Python Class  | Purpose  |
|---|---|---|---|---|
| Resource / Literal | librdf_node | redland::Node | RDF.Node | RDF Model & Syntax nodes |
| Statement / Triple | librdf_statement | redland::Statement | RDF.Statement | RDF Model & Syntax arcs (statements, triples) [isa Resource] |
| Model | librdf_model | redland::Model | RDF.Model | Set of Statements usually held in one Storage. |
| Storage | librdf_storage | redland::Storage | RDF.Storage | Storage for Models either persistant or in-memory. |
| Stream | librdf_stream | redland::Stream | RDF.Stream | Providing sequences of Statements from Parsers, queries. |
| Parser | librdf_parser | redland::Parser | RDF.Parser | Syntaxes parsers delivering Stream of Statements or writing to a Model |
| Query | librdf_query | redland::Query | RDF.Query | Querying of an Model delivering a QueryResults |
| QueryResults | librdf_query_results | redland::QueryResults | RDF.QueryResults | Results of applying an Query to a Model giving either variable bindings with Node values or Stream of Statements |
| Serializer | librdf_serializer | redland::Serializer | RDF.Serializer | Serializes a Model into a syntax such as RDF/XML |
| Iterator | librdf_iterator | redland::Iterator | RDF.Iterator | Enumerating lists (of Node) from queries. |
| URI | librdf_uri | redland::Uri | RDF.Uri | Provides URIs for Resources, Parsers, ... |
| World |   | redland::World | RDF.World | RDF wrapper class handling Redland startup/shutdown |
| Digest | librdf_digest | |   | Internal content digest class |
| Hash | librdf_hash | |   | Internal key:value maps class |

**Comment by mbjones** [comment]
API was implemented as above.  The table needs to be added to the R package documentation, then this issue can be closed.

**Comment by sbpcs59** [comment]
This information has been included in the package level docs, e.g. ?redland

commit fefb6fc34e75ce425ebd29a43db10fbde68f5a02
