### ISSUE TITLE
Do we need all the python/php/etc?

### ISSUE THREAD

**Issue by Ironholds** [ropensci/redland-bindings#22]
I'm wondering if it might not be a better idea, rather than forking off redland-bindings, to create a dedicated rdf repo that just embeds the RDF C library, in the same way that (say) xml2 includes libxml to maximise portability.

(This might be premature/overthinking, though)

**Comment by cboettig** [comment]
@Ironholds This makes it easier to send a pull-request back to the official redlands-bindings that will add support for R.  Note that R users will have no need to ever download or see those files, they will be able to directly install the R package from CRAN or whatever that just happens to be built from these scripts but contains only what is needed to run on R.  I think this is the best of both worlds in avoiding fragmentation and contributing back upstream in a way consistent with the existing standard, while also providing a friendly user end.  @sbpcs59 and @mbjones have been doing all the real work though so I leave them to chime in.  I think they might appreciate your use-cases re RDF and RDFA though too.

**Comment by mbjones** [comment]
Yeah, the goal is to be able to fork and PR back to the upstream repository.  We are close but not yet quite ready to install directly into R from the R/redland package directory, and once that is working, then both install.packages() and install_github() will work without the rest of the code.  But we send pull requests back easily this way.

**Comment by Ironholds** [comment]
Gotcha!

**Comment by mbjones** [comment]
Installation is working now from the R/redland subdirectory.  Parent directories maintain the relationship to the upstream redland-bindings repository.  We'll issue a pull request to merge soon, but closing this question now.
