### ISSUE TITLE
Prepare windows binary package for CRAN submission

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/redland-bindings#30]
Build a windows distribution for redland-bindings as described in 

http://cran.r-project.org/doc/manuals/r-release/R-admin.html#Windows-packages

and 

http://cran.r-project.org/doc/manuals/r-release/R-admin.html#Windows-packages

Note: building the redland-bindings binary packages for windows is dependent on the
availability of windows builds for redland rdf.

**Comment by jeroenooms** [comment]
Static libraries for librdf are now on rwinlib: https://github.com/rwinlib/redland. See also PR https://github.com/ropensci/redland-bindings/pull/35.

**Comment by sbpcs59** [comment]
The static libraries and redland package binaries build config have been built with
Rtools 3.2 (for R 3.1.x to 3.2.x) and tested on Windows 7, Windows 10 with all unit tests passing.
