### ISSUE TITLE
Evaluate 'homebrew' as recommended redland RDF library install tool for Mac OS X

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/redland-bindings#32]
Macports is a staple for developers on Mac OS X, but can be a heavyweight option for installing the
redland libraries on OS X for non-developers, as many packages have to be installed and
updated often. The homebrew installation tool (http://brew.sh) is much lighter weight and installs/links to 
/usr/local instead of /opt/local as mac ports does.

Also, by default, OS X, looks in /usr/local for shared libraries. (However, this can be overridden by
defining the DYLD_LIBRARY_PATH environment variable)

Evaluate the use of this tool for installing the libraries needed by the redland package and 
add this recommendation to the R/redland/Readme.md if it looks good.

**Comment by mbjones** [comment]
Supporting homebrew is a great goal.  It has its own issues -- @amoeba reports that there can be trouble with developer tools installed in /usr/local, particularly homebrew, when upgrading to El Capitan. He indicated that upgrades where /usr/local already exists can be made to work, but there can be issues with creating /usr/local on El Cap due to new security restrictions.

**Comment by amoeba** [comment]
I was about to link in a very informative GitHub Issue on the homebrew repo but I then found this extremely straight-forward description of the problems and fixes.

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md

For people who aren't using homebrew already and who **are** on El Capitan, it looks like homebrew could be tough to recommend as installing it in /usr/local will require rebooting into Recovery Mode for those users. Installing Homebrew into alternative locations is not recommend by the developer but it can be done, see:

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Installation.md#alternative-installs

Given that homebrew is so popular, I would still recommend including a guide for install Redland using it, regardless of these /usr/local issues.

Hopefully that'll help clear anything up.

**Comment by amoeba** [comment]
Also, with my homebrew-installed copy of redlands, the redlands R package off the NCEAS drat repo installs and works just fine on my El Capitan system.

**Comment by sbpcs59** [comment]
@amoeba I'm really hoping that Apple doesn't restrict /usr/local. It's not completely clear whether a third party app will have to be Apple approved (signed?) in order to write to this directory:

https://support.apple.com/en-us/HT204899

**Comment by sbpcs59** [comment]
Installing redland libraries has been tested with Homebrew on Mac OS X Yosemite 10.10.5 and El Capitan 10.11.1, provided that MacPorts has not been installed. Homebrew is supposed to work
with MacPorts but we ran into problems trying to do this. The redland Readme now recommends to
use MacPorts if it is currently installed, and to use Homebrew if MacPorts is not installed.
