### ISSUE TITLE
Resolve 'generic function' message

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/redland-bindings#38]
When running devtools::test() the following message is printed:

```
> test()
Loading redland
Creating a generic function for ‘print’ from package ‘base’ in package ‘redland’
Testing redland
```

Determine why this 'generic function' message is printed, if something needs to be fixed in redland, and
how to prevent this message from being printed.

**Comment by mbjones** [comment]
it also happens running `library(redland)` for an installed package.

**Comment by sbpcs59** [comment]
This message is printed when 'redland.R' is loaded and the following line is evaluated:

```
setMethod('print', 'ExternalReference',
function(x) {print(as(x, "character"))})
```

The warning is printed because a method is being set for 'print' but no generic has been defined,
so R creates the generic definition in the base package:

```
standardGeneric for "print" defined from package "base"

function (x, ...) 
standardGeneric("print")
<environment: 0x105ab9638>
Methods may be defined for arguments: x
Use  showMethods("print")  for currently available ones.
```

This print method isn't used by the redland package anywhere, so I would prefer to
disable it, even if it means editing the generated 'redland.R' file

**Comment by mbjones** [comment]
I agree, that would be great to eliminate, but please be sure to make it an automated process as part of the build.

**Comment by sbpcs59** [comment]
This has been fixed in the generated R/redland.R file and a git PR has been issued
for a fix in the swig source that generates this file: https://github.com/swig/swig/pull/633
