### ISSUE TITLE
Error loading package from R command line

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/redland-bindings#41]
If the CRAN built OS X redland.so is installed, the redland package cannot be loading
from the R command line on Mac OS X:

> library(redland)
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/slaughter/R/x86_64-darwin-library/3.2/redland/libs/redland.so':
  dlopen(/Users/slaughter/R/x86_64-darwin-library/3.2/redland/libs/redland.so, 6): Library not loaded: /private/tmp/homebrew/opt/rasqal/lib/librasqal.3.dylib
  Referenced from: /Users/slaughter/R/x86_64-darwin-library/3.2/redland/libs/redland.so
  Reason: image not found

## Lengthy explanation of the problem
This error is not seen with R.app, Rstudio or if the redland package is installed from source and
built locally. The reason for this problem with the R command is that the environment variable
"DYLD_FALLBACK_LIBRARY_PATH" is being set incorrectly to not include "/usr/local/lib" which is
the location of librasqal.dylib, libraptor2.dylib installed from brew. The setting of this env var is in disagreement with the Apple docs at https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/dyld.1.html
which state:

```
    DYLD_FALLBACK_LIBRARY_PATH
              This  is  a  colon  separated  list  of directories that contain libraries.  It is used as the
              default location for libraries not found in their install path.  By  default,  it  is  set  to
              $(HOME)/lib:/usr/local/lib:/lib:/usr/lib.
```

Since redland.so on CRAN is linked to librasql.dylib, libraptor2.dylib installed in /tmp, when this .so
is downloaded to the user machine, it 'falls back' to the libraries found in the search path specified by
the env var.

## Potential fixes

- [ ] Change install instructions to have all OS X users install redland from source
- [ ] Build CRAN binaries with libraptor*, librasqal* installed in /usr/local (not sure if CRAN will let us do this)
- [ ] Have users set the DYLD_LIBRARY_PATH in ~/.Renviron
- [ ] Convince CRAN to set the env var to include /usr/local

**Comment by cboettig** [comment]
@jeroenooms have you seen something like this before?  Any thoughts on the best option?

**Comment by jeroenooms** [comment]
Sorry this is probably an error in my configure script. Will push a fix soon. 

It should simply statically link all dependencies at build time, so that nothing is required at runtime.

**Comment by jeroenooms** [comment]
This should fix it https://github.com/ropensci/redland-bindings/pull/42. Sorry about that.

**Comment by sbpcs59** [comment]
Confirmed that https://github.com/ropensci/redland-bindings/pull/42 (merge 2696bc6aac077dff90ac415f97f853d17093e392) fixes the problem. The resulting redland.so does
not contain references to any of the librdf, librasqal, libraptor dylibs:

```
$ otool -L src/redland.so
src/redland.so:
redland.so (compatibility version 0.0.0, current version 0.0.0)    /usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
    /usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
    /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
    /usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 55.1.0)
    /usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
    /Library/Frameworks/R.framework/Versions/3.2/Resources/lib/libR.dylib (compatibility version 3.2.0, current version 3.2.3)
    /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1255.1.0)
```

**Comment by jeroenooms** [comment]
Great, let me know when you release to CRAN, then I'll double check that everything works as expected.
