### ISSUE TITLE
'assert' in redland.c generates devtools::check() warning

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/redland-bindings#45]
The following warning is seen when the package is submitted to http://win-builder.r-project.org:

```
* checking compiled code ... WARNING
File 'redland/libs/i386/redland.dll':
  Found '_assert', possibly from 'assert' (C)
    Object: 'redland.o'

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor the system RNG.
```

This error is not seen when devtools::check() is run on Windows.

This file redland.c hasn't been updated in a year, so I'm thinking that the win-builder checks
are maybe a bit more stringent that the actual CRAN checks, and that this problem won't
be flagged during package submission.

**Comment by jeroenooms** [comment]
This is fixed by https://github.com/ropensci/redland-bindings/pull/47

**Comment by sbpcs59** [comment]
Excellent! Verified with win.builder for R version 3.2.5 (2016-04-14) and R version 3.3.0 beta (2016-04-14 r70486).
