### ISSUE TITLE
Prepare for package release of version 1.0.17-8

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/redland-bindings#46]
The following items are required before package release:

- [x] test Windows 32 bit, gcc 4.9.3 fix (commit bace77f48ee12cf4c4ac23db09b51f45f9acf21e)
- [x] test Mac OS X install with librdf statically linked in to redland.so (commit 69e743ce824c67c72e574e9215070dab51948eab)
- [x] update cran-comments.md
- [x] update README.md
- [x] update version, pub date in DESCRIPTION
- [x] check build on win-builder
  - a problem with this item is described in https://github.com/ropensci/redland-bindings/issues/45

**Comment by sbpcs59** [comment]
@mbjones redland is now ready for submission to CRAN.

**Comment by jeroenooms** [comment]
Thanks for the release. I confirmed that the package now works on osx and windows without installing any dependencies. Sorry for not getting this right the first time.

**Comment by sbpcs59** [comment]
@jeroenooms Thanks for your efforts in making package installation easier. This will really help
with ease of installation of downstream packages, like dataone (soon to be on CRAN).

**Comment by sbpcs59** [comment]
redland 1.0.17-8 was published on CRAN 04/26/2016.
