### ISSUE TITLE
README in html

### ISSUE THREAD

**Issue by karthik** [ropensci/redland-bindings#48]
The readme is in html which Github does not render outside of the `gh-pages` branch. You might consider just converting it to markdown and deleting the html version.

**Comment by mbjones** [comment]
Agrred, @karthik, but probably not on this one. This repo is a fork of the redland-bindings main repo, which we do not maintain.  The R/redland/Readme.md file is the main readme for the R package that we are contributing back to upstream, and we made that in Markdown.  We've asked for a number of upstream bug fixes to code, and they haven't been addressed yet.  So, I'm not sure when we might be able to push suggestions like that upstream.  In the meantime, we're just leavint the root directories alone and working inside the R subdirectory.
