### ISSUE TITLE
Missing class definitions in generated R wrapper code

### ISSUE THREAD

**Issue by mbjones** [ropensci/redland-bindings#5]
SWIG generates both a C code file with wrapper functions and the corresponding R code to call those c routines.  However, the R code is missing class definitions for at least 2 of the C data structures.  By adding these class definitions, the functions seem to be callable without any errors.  Find a way to add them automatically during the swig build.  Maybe as a swig template?  The missing R code that I inserted is in the following patch:

``` diff
diff --git a/R/redland/R/Redland.R b/R/redland/R/Redland.R
index 61333b1..7c4edab 100644
--- a/R/redland/R/Redland.R
+++ b/R/redland/R/Redland.R
@@ -5,7 +5,7 @@
 # the SWIG interface file instead.

 ##   Generated via the command line invocation:
-##      swig -v -r -namespace -outdir redland/R -o redland/src/redland.c Redland.i
+##      swig -v -Wall -r -namespace -outdir redland/R -o redland/src/redland.c Redland.i


 #                         srun.swg                            #
@@ -172,7 +172,8 @@ setClass('_p_librdf_storage_s', contains = 'ExternalReference')
 setClass('_p_librdf_stream_s', contains = 'ExternalReference')
 setClass('_p_librdf_parser_s', contains = 'ExternalReference')
 setClass('_p_librdf_serializer_s', contains = 'ExternalReference')
-
+setClass('_p_librdf_query', contains = 'ExternalReference')
+setClass('_p_librdf_query_results', contains = 'ExternalReference')


 setMethod('[', "ExternalReference",
```

**Comment by gothub** [comment]
It appears that this issue was resolved an these symbols are now included in the input Redland.i, and then the generated R and C code, since commit 5fbc9290bea322caa2e734ae5df4fcfe39a684c8
