### ISSUE TITLE
How to read TTL file into model?

### ISSUE THREAD

**Issue by NovasTaylor** [ropensci/redland-bindings#55]
Is is possible to read from a .TTL source file (to parse it into the model)?

This code appears to work without error for a .RDF file:
library(redland)
setwd("C:/foo")
world <- new("World")
storage <- new("Storage", world, "hashes", name="", options="hash-type='memory'")
model <- new("Model", world=world, storage, options="")
parser <- new("Parser", world)
parseFileIntoModel(parser, world, "rdf/ct-schema.rdf", model)

But when attempting to read a TTL file using the command:
parseFileIntoModel(parser, world, "rdf/myTurtle.TTL", model)

I get the message:
librdf error - XML parser error: Document is empty

Is there an option/syntax for reading TTL ? I can output to TTL using redland without error.
Cheers,

Tim

**Comment by mbjones** [comment]
It would be analogous to the RDF/XML parsing code, but you would use `turtle` for the format name and `text/turtle` for the mime type.  Note the list of format names and corresponding mime types at the end for reference.

```r
library(redland)
setwd("C:/foo")
world <- new("World")
storage <- new("Storage", world, "hashes", name="", options="hash-type='memory'")
model <- new("Model", world=world, storage, options="")

parser <- new("Parser", world, name = 'turtle', mimeType = 'text/turtle')
redland::parseFileIntoModel(parser, world, "rdf/ct-schema.ttl", model)

# Format details: Must match parser name & q 1.0 mimetype listed at:
# http://librdf.org/raptor/api/raptor-formats-types-by-parser.html
rdf_mimetypes <- c("nquads" = "text/x-nquads",
                   "ntriples" = "application/n-triples",
                   "rdfxml" = "application/rdf+xml",
                   "trig" = "application/x-trig",
                   "turtle" = "text/turtle")
```

These format names and mime types should be documented in the Parser class, so I'll make a note to add them.

**Comment by mbjones** [comment]
See related discussion documentation and of a simpler conversion API in #52 .

**Comment by NovasTaylor** [comment]
This works and returns the first result. I assume that getNextResult must be wrapped in a function (loop) that returns each next triple result until NULL is returned. Is there a "getAllResults" function under consideration?

**Comment by mbjones** [comment]
You have to query the model to see the triples that were added. See the
vignette for an example SPARQL query over the model.

Matt

**Comment by NovasTaylor** [comment]
The vignette on CRAN (https://github.com/cran/redland/blob/master/vignettes/) led me to create my own loop over getNextResult to return all results :  "Additional results can be obtained by calling getNextResult() until a null value is returned, which indicates that all results have been returned."  

I want to ensure I follow the preferred (and most efficient) way to get the entire query result.
Cheers!

**Comment by cboettig** [comment]
Closing as this appears to be resolved. 

@NovasTaylor trying out a higher-level wrapper to automate some of this stuff. Take a look at https://github.com/cboettig/rdflib for a simplified syntax for things like parsing turtles or querying all results from a sparql query. Feedback welcome.  

(We're building in a separate package since it is easier to maintain/develop that way without messing with the stable low-level bindings here).

**Comment by gothub** [comment]
Closing per @cboettig above msg.
