### ISSUE TITLE
fix NOTE on lack of new_roclet symbol

### ISSUE THREAD

**Issue by mbjones** [ropensci/redland-bindings#72]
Our CRAN check page reports that `new_roclet` is an undefined symbol:

```
checking R code for possible problems ... [9s/9s] NOTE
mergeNamespace_roclet: no visible global function definition for
  ‘new_roclet’
Undefined global functions or variables:
  new_roclet
```

Check and fix this.

**Comment by gothub** [comment]
@mbjones this should have been fixed in commit a5c97142753a374b3acf4f5dff589fd7a2221924 with updates for Roxygen 6.0.1, when the associated Roxygen function name changed.

**Comment by mbjones** [comment]
Hmm. For some reason that was not getting picked up in my build from master.  Can you verify that a clean build from master includes this fix?

**Comment by gothub** [comment]
Good idea. I just now built redlands (master branch)  from a freshly cloned project then built and checked on:
- macos 10.13.5
   - check results: 
R CMD check results
0 errors | 0 warnings | 0 notes
- win-builder R version 3.5.1 (2018-07-02)
  - check status (1 NOTE):
  checking installed package size ... NOTE
  installed size is  6.0Mb
  sub-directories of 1Mb or more:
    libs   5.0Mb
  (This is the usual NOTE, explained in 'cran-comments.md')
-  win-builder R Under development (unstable) (2018-07-01 r74950)
   - check status (0 errors | 0 warnings | 0 notes):
      (This is a bit interesting in that the check didn't complain about library sizes but was run under x86_64-w64-mingw32 (64-bit))
- win-builder R version 3.4.4 
  - check status (2 notes)
    - Possibly mis-spelled words in DESCRIPTION:
      RDF (3:8, 16:51, 16:57, 17:27, 17:77, 18:69)
      Redland (17:69)
      (Both RDF and Redland are explained in the DESCRIPTION)
   - checking installed package size ... NOTE
     installed size is  5.8Mb
     sub-directories of 1Mb or more:
     libs   5.0Mb

**Comment by cboettig** [comment]
On the possible spell check issue: @jeroen notes that if you add `Language` to your description file, CRAN will skip the spell check.  Also recommends `spelling::spell_check_setup()` or `usethis::use_spell_check()` to set up a WORDLIST so that R doesn't flag them (I think).

**Comment by gothub** [comment]
@cboettig Running `spelling::spell_check_setup()` adds the `Language` directive to `DESCRIPTION`, adds `inst/WORDLIST` and also adds a unit test to run the spelling check . Nice!

Added these generated files in commit c2931bda2e93fc819ecac6fe330817c017a0f613

**Comment by jeroen** [comment]
Can we try to schedule a CRAN release? Because this has a fix for the upcoming new windows toolchain.

**Comment by gothub** [comment]
The original topic of this issue (commit commit a5c9714 ) has been verified on both macOS and Windows 7.
