### ISSUE TITLE
CRAN build errors

### ISSUE THREAD

**Issue by gothub** [ropensci/redland-bindings#75]
The redland 1.0.17-10 CRAN  build generated an ERROR for `r-release-windows-ix86+x86_64`:
https://cran.r-project.org/web/checks/check_results_redland.html

From the [install log](https://www.r-project.org/nosvn/R.check/r-release-windows-ix86+x86_64/redland-00install.html):
```
** byte-compile and prepare package for lazy loading
Error in namespaceExport(ns, exports) : 
  undefined exports: %s!=%, %s!==%, %s+%, %s<%, %s<=%, %s==%, %s===%, %s>%, %s>=%, %stri!=%, %stri!==%, %stri+%, %stri<%, %stri<=%, %stri==%, %stri===%, %stri>%, %stri>=%, stri_datetime_add<-, stri_sub<-, stri_subset<-, stri_subset_charclass<-, stri_subset_coll<-, ...
ERROR: lazy loading failed for package 'redland'
```
@jeroen could this be related to the new toolchain?

We did make changes to `redland/src/redland.c` for the redland shared library/dll symbol lookup in `R_init_redland`, but I'm not sure that this is the problem, as this is working for win-builder builds and other platforms.

Any ideas?

**Comment by jeroen** [comment]
This looks like a temporary problem on the CRAN servers due to the stringi package which was updated today. Try again tomorrow.

**Comment by jeroen** [comment]
Why do you have a runtime dependency on roxygen2 by the way? roxygen is a tool for development, you don't need to have a formal dependency on it in your package.

**Comment by gothub** [comment]
The redland/Windows builds have all passed: https://cran.r-project.org/web/checks/check_results_redland.html

@jeroen good point regarding the `roxygen2` dependency, I'll remove it from DESCRIPTION

**Comment by jeroen** [comment]
Make sure to also remove from the `NAMESPACE`
