### ISSUE TITLE
generate NAMESPACE from multiple sources

### ISSUE THREAD

**Issue by mbjones** [ropensci/redland-bindings#9]
The R NAMESPACE file is generated by SWIG for the classes and code that SWIG generates.  However, this NAMESPACE file is incomplete, as it is missing the proper DynLib calls, and it is missing the statements that would normally be generated from ROxygen.  I have added a NAMESPACE.in file which contains these additions, and the makefile then generates the true NAMESPACE by concatenating NAMESPACE.in with the generated NAMESPACE file.  However, if one runs `devtools::document()` after make, then it will overwrite the NAMESPACE file and omit all of the SWIG-generated lines, because SWIG doesn't generate ROxygen @export tags.  So, we need to make all of this build infrastructure robust so both make and document() can work properly.

**Comment by sbpcs59** [comment]
The NAMESPACE file generated by SWIG causes an error when the package is installed, due to the exportMethods directives that it generates for SWIG function calls.

**Comment by sbpcs59** [comment]
The mergeNamespace roclet was rewritten to dynamically determine the set of SWIG functions to
add to the NAMESPACE file by loading the wrapper file 'R/redland.R' and inspecting each loaded function. This fix is in commit https://github.com/ropensci/redland-bindings/commit/db9d67831724b712a8ddfe84873a26571fac6136
