### ISSUE TITLE
Configure fails on macOS if redland not already installed

### ISSUE THREAD

**Issue by gothub** [ropensci/redland-bindings#91]
During package build and install, the `configure` script fails on macOS if the dependent redland package is not already installed. If the package has been previous installed the build/install succeeds.

This was not caught in testing because rhub pre-installs dependent packages listed in DESCRIPTION. CRAN does not pre-install these packages, at least not for macOS. Note that configure does not pre-install dependent packages for Linux or Windows. In any case, this problem needs to be resolved as this is causing ERRORs on CRAN, and will make installs harder for macOS users.

@jeroen if you have a minute, could you review `configure`, which has been upgraded to pass `checkbashisms`, and verify that all changes are correct.

**Comment by gothub** [comment]
These items need to be added for pre-release testing:
- test macOS install when redland RDF libraries are not installed
- test macOS install when brew is not installed
- test macOS install when pkg-config is not installed

**Comment by jeroen** [comment]
This doesn't work, the `"$PLATFOR` environment variable in your configure doesn't exist?

**Comment by jeroen** [comment]
I fixed it here: https://github.com/ropensci/redland-bindings/commit/08479901597d13d62bea549570e34566885c4210

**Comment by gothub** [comment]
Great, thanks

**Comment by gothub** [comment]
Fixed in commit 08479901597d13d62bea549570e34566885c4210

**Comment by gothub** [comment]
Added add'l check to verify that both brew and redland brew packages are installed for macOS, otherwise autobrew is used. Added in commit d04ecdb92cc50ed5bca57722603dbf809fe7e1ca

**Comment by jeroen** [comment]
OK, sounds good 👍
