### ISSUE TITLE
update release for ucrt win binaries

### ISSUE THREAD

**Issue by mbjones** [ropensci/redland-bindings#93]
@jeroen committed changes to fix binary builds for windows in sha e487922.

Need to incorporate this into a release. While at it, reassess the status of issue #92, which seemed like it was imminent. @gothub could you update this release?

**Comment by jeroen** [comment]
Looks like [v.1.0.17-14 ](https://github.com/ropensci/redland-bindings/releases/tag/v.1.0.17-14) tags a commit from Oct 21, 2020, which does not include the two commits that we actually need.

**Comment by mbjones** [comment]
Yeah, I think that was just houusekeeping on the previous release. 

@gothub please let us know when you can return to this and push Jeroen's changes into a release to CRAN. Thanks.

**Comment by mbjones** [comment]
Included in the 1.10.17-15 release.
